train_dataset:
    dataset:
        root_path: ./data/train
        repeat: 1
        scale_min: 2
        scale_max: 8
        augment: True
    batch_size: 10

val_dataset:
    dataset:
        root_path: ./data/val
        repeat: 1
        scale_min: 4
        scale_max: 4
        augment: False  
    batch_size: 1

data:
    channels: 3
    logit_transform: False
    uniform_dequantization: False
    gaussian_dequantization: False
    rescaled: True

model:
    type: "simple"
    image_size: 256
    in_channel: 6
    out_channel: 3
    inner_channel: 64
    norm_groups: 16 #32
    channel_mults: [1, 2, 2, 4, 4, 8] #[1, 2, 2, 2, 4, 4, 4]
    res_blocks: 1 # 2
    attn_res: [16, ]
    dropout: 0.2
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    with_noise_level_emb: True
    srno:
        encoder: edsr-baseline
        no_upsampling: True
        width: 256
        blocks: 16

diffusion:
    beta_schedule: linear
    beta_start: 0.000001
    beta_end: 0.01
    num_diffusion_timesteps: 2000

training:
    n_epochs: 10000
    epoch_save_freq: 10

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    beta1: 0.9
    amsgrad: False
    eps: 0.00000001

scheduler:
    lr_sequence: [1e-4, 8e-5, 6e-5, 4e-5, 2e-5, 1e-5, 8e-6, 6e-6, 4e-6, 2e-6]
    step_size: 100000

srno_weight: ./srno_weight.pth
