train_dataset:
    dataset:
        # root_path: ./data/AID_600/train
        root_path: ./data/SIOR/train
        # lr_path: ./data/AID/train_LR_x4
    
        repeat: 9
    wrapper:
        inp_size: 64
        scale_min: 4
        scale_max: 4
        augment: True
        # train: True
        
    batch_size: 10

val_dataset:
    dataset:
        # root_path: ./data/AID_600/val
        root_path: ./data/SIOR/val
        # lr_path: ./data/AID/val_LR_x4
        
        repeat: 1
    wrapper:
        inp_size: 64
        scale_min: 4
        scale_max: 4
        augment: False
        # train: False
        
    batch_size: 1

data:
    channels: 3
    image_size: 256
    logit_transform: False
    uniform_dequantization: False
    gaussian_dequantization: False
    rescaled: True

model:
    type: "simple"
    in_channels: 6
    out_ch: 3
    ch: 64
    ch_mult: [1, 1, 2, 2, 4, 4] #[1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True
    srno:
        encoder: edsr-baseline
        no_upsampling: True
        width: 256
        blocks: 16

diffusion:
    beta_schedule: linear
    beta_start: 0.000001 #0.0001
    beta_end: 0.01 #0.02
    num_diffusion_timesteps: 2000

training:
    n_epochs: 10000
    epoch_save_freq: 3

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.0001
    beta1: 0.9
    amsgrad: False
    eps: 0.00000001
    # grad_clip: 100.0
